# Prometheus configuration для Telegram Mini App
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Main Application
  - job_name: 'telegram-mini-app'
    static_configs:
      - targets: 
        - 'main_app:5000'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s

  # PostgreSQL
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # User Services (микросервисы)
  - job_name: 'user-service'
    static_configs:
      - targets: ['user_service:5001']
    metrics_path: '/metrics'

  - job_name: 'channel-service'
    static_configs:
      - targets: ['channel_service:5002']
    metrics_path: '/metrics'

  - job_name: 'offer-service'
    static_configs:
      - targets: ['offer_service:5003']
    metrics_path: '/metrics'

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics_service:5004']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification_service:5005']
    metrics_path: '/metrics'

  # RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'