version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///telegram_mini_app.db
      - SECRET_KEY=dev-secret-key
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBAPP_URL=http://localhost:5000
      - DEBUG=True
    volumes:
      - .:/app
    restart: unless-stopped
    command: ["python", "working_app.py"]

networks:
  default:
    driver: bridge